### ISSUE TITLE
Confluence page is private

### ISSUE THREAD

**Issue by matthijskooijman** [City-of-Helsinki/tilavarauspalvelu-core#1245]
The README links to https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/887029864/Tilavarauspalvelu+Varaamo for more information, but that page is private (even when I'm logged in to confluence). It shows a button to request access, but that does not seem to work.

![image](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/assets/194491/73234b1e-bbf6-4829-be6e-798e14614fbd)

Would it make sense to make this page (and maybe others) public?

**Comment by matti-lamppu** [comment]
Hi! The Confluence pages are private on purpose since they are meant for people working in [City-of-Helsinki](https://github.com/City-of-Helsinki) projects, and so the links won't be made public. I'm sorry for the inconvenience.

**Comment by matthijskooijman** [comment]
Thanks for you response. Maybe clarify this is in the github README, then? Now it looks like it is intended to provide additional public information for anyone that wants to use this code, but it is accidentally private.

**Comment by matti-lamppu** [comment]
Noted, we'll adjust the language👍
